export const defaultContent = {
  profile: {
    name: 'Chiboub Taha Adnane',
    title: 'Software Engineer Student',
    description: 'Computer science engineering student focused on modern web applications, scalable architecture, and polished user experience.',
    email: 'taha.adnane.chiboub@gmail.com',
    github: 'https://github.com/tchiboub-dot',
    linkedin: 'https://www.linkedin.com/in/taha-adnane-chiboub-1a5ab939a',
    photo: '/photo-profil.jpg',
    cvPath: '/cv-taha-adnane-chiboub.pdf',
  },
  about: {
    title: 'About Me',
    subtitle: 'Computer science engineering student focused on impactful products, scalable architecture, and polished user experience',
    introduction: 'I am a computer science engineering student passionate about building modern digital products.',
    description: 'I enjoy turning ideas into production-ready web experiences by combining strong frontend execution with practical backend fundamentals.',
    interests: ['Full-stack web development', 'Cloud architecture', 'User-focused design', 'AI-powered applications'],
    languages: ['Arabe (Natif)', 'Français (Courant)', 'Anglais (Intermédiaire)'],
    availability: 'Available for internships, freelance work, and collaborative product building.',
  },
  projects: [
    { id: 'project-parfume-store', title: 'Parfume Store', category: 'Web Apps', summary: 'Premium full-stack e-commerce experience with modern UI, multilingual flows, and polished performance.', techStack: ['React', 'Next.js', 'Tailwind', 'TypeScript'], githubLink: 'https://github.com/tchiboub-dot/parfume', liveLink: 'https://parfume-store-eta.vercel.app/en', preview: '/projects/parfume-store-preview-real.jpg', sortOrder: 0, featured: true },
    { id: 'project-student-management', title: 'Student Management System', category: 'Web Apps', summary: 'CRUD-focused platform for student operations with practical authentication and clean dashboard UX.', techStack: ['React', 'Node.js', 'MongoDB', 'JavaScript'], githubLink: 'https://github.com/tchiboub-dot', liveLink: 'https://student-management5.vercel.app/', preview: '/projects/student-management-preview.png', sortOrder: 1, featured: true },
    { id: 'project-security-headers', title: 'Security Headers Verifier', category: 'Tools', summary: 'Developer utility to validate modern HTTP security headers and improve deployment hardening.', techStack: ['Next.js', 'Node.js', 'Security Headers', 'Vercel'], githubLink: 'https://github.com/tchiboub-dot/security-headers', liveLink: 'https://security-headers-2owb.vercel.app/', preview: '/projects/security-headers-preview.png', sortOrder: 2, featured: false },
    { id: 'project-maison-elegance', title: 'Maison Élégance', category: 'Web Apps', summary: 'Restaurant platform with menu interaction, reservations, and conversion-focused responsive design.', techStack: ['HTML', 'CSS', 'JavaScript', 'Responsive UI'], githubLink: 'https://github.com/tchiboub-dot', liveLink: 'https://maisonelegance-one.vercel.app/', preview: '/projects/maison-elegance-preview.png', sortOrder: 3, featured: false },
  ],
  skills: {
    frontend: [{ name: 'HTML', level: 92 }, { name: 'CSS', level: 88 }, { name: 'JavaScript', level: 84 }, { name: 'React', level: 80 }, { name: 'Next.js', level: 78 }],
    backend: [{ name: 'Node.js', level: 76 }, { name: 'Express', level: 72 }, { name: 'Python', level: 74 }, { name: 'MongoDB', level: 70 }, { name: 'PostgreSQL', level: 66 }],
    tools: [{ name: 'Git', level: 86 }, { name: 'Docker', level: 64 }, { name: 'Vercel', level: 82 }, { name: 'Figma', level: 69 }],
    aiCloud: [{ name: 'OpenAI API', level: 72 }, { name: 'Cloud Deployment', level: 74 }, { name: 'WebRTC', level: 60 }],
  },
  experience: [{ id: 'experience-current', title: 'Full-Stack Developer (Junior)', company: 'Personal & Academic Projects (ESISA)', location: 'Fès, Maroc', period: '2025/2026 – Présent', type: 'Hands-on Product Building', achievements: ['Developed responsive web applications using React, Next.js, and Node.js patterns.', 'Improved UI consistency by building reusable component blocks for faster iteration.', 'Optimized API and form flows to reduce friction and improve user task completion.', 'Shipped and maintained demo deployments with iterative UX and performance enhancements.'], current: true, sortOrder: 0 }],
  education: [{ id: 'education-esisa', degree: 'Cycle Ingénieur en Informatique', institution: 'ESISA Fes', location: 'Fès, Maroc', period: '2025/2026 – Présent', description: "Formation en informatique couvrant l'algorithmique, la programmation, les systèmes, la logique et les bases du développement logiciel.", highlights: ['Algorithmique et structures de données', 'Programmation orientée objet', "Systèmes d'exploitation et réseaux", "Développement d'applications web"], keySkillsDeveloped: ['Algorithms and data structures', 'Software architecture', 'System design', 'Programming best practices'], current: true, sortOrder: 0 }],
  certifications: [
    { id: 'cert-ai-business', image: '/certificates/certificate-ai-business.jpg', title: 'AI Business Certificate', issuer: 'HP LIFE / HP Foundation', year: '2026', summary: 'Credential focused on practical AI applications in business workflows and decision-making contexts.', verification: 'Credential verified through HP LIFE completion records.', skills: ['AI Business Use Cases', 'Decision Workflows', 'Digital Strategy'], description: 'Builds practical understanding of applying AI to business processes, communication, and decision support.', sortOrder: 0 },
    { id: 'cert-prompt-engineering', image: '/certificates/certificate-prompt-engineering.jpg', title: 'Prompt Engineering Certificate', issuer: 'Simplilearn SkillUp', year: '2026', summary: 'Certification on designing effective prompts, prompt patterns, and reliable AI-assisted output workflows.', verification: 'Credential ID: 9808496', skills: ['Prompt Design', 'Context Structuring', 'Output Quality Control'], description: 'Covers prompt design structure, response quality control, and repeatable prompt strategies for AI tools.', sortOrder: 1 },
    { id: 'cert-cybersecurity', image: '/certificates/certificate-cybersecurity.jpg', title: 'Cybersecurity Fundamentals', issuer: 'HP LIFE / HP Foundation', year: '2026', summary: 'Covers modern cybersecurity principles, risk awareness, and secure digital best practices.', verification: 'Credential verified through HP LIFE completion records.', skills: ['Security Basics', 'Threat Awareness', 'Secure Practices'], description: 'Validates foundational cybersecurity literacy, including risk awareness and safer digital operational habits.', sortOrder: 2 },
    { id: 'cert-c-programming', image: '/certificates/certificate-c-programming.png', title: 'C Programming Certificate', issuer: 'Simplilearn SkillUp', year: '2026', summary: 'Fundamental-to-advanced C programming concepts including control flow, memory, and structured design.', verification: 'Credential ID: 9698550', skills: ['C Language', 'Memory Concepts', 'Structured Programming'], description: 'Confirms competence in core C language principles, memory concepts, and structured problem-solving patterns.', sortOrder: 3 },
    { id: 'cert-agile', image: '/certificates/certificate-agile.jpg', title: 'Agile Project Management', issuer: 'HP LIFE / HP Foundation', year: '2026', summary: 'Training in agile project delivery, iterative planning, collaboration, and product execution discipline.', verification: 'Credential verified through HP LIFE completion records.', skills: ['Agile Delivery', 'Collaboration', 'Iteration Planning'], description: 'Demonstrates practical agile planning and collaboration methods for iterative, delivery-focused execution.', sortOrder: 4 },
  ],
  contact: { email: 'taha.adnane.chiboub@gmail.com', linkedin: 'https://www.linkedin.com/in/taha-adnane-chiboub-1a5ab939a', github: 'https://github.com/tchiboub-dot', cvPath: '/cv-taha-adnane-chiboub.pdf' },
}
